version: "3.7"
services:
  tools:
    build:
      context: ./
    cap_add:
      - SYS_PTRACE
    environment: 
      - container=docker
      - TZ=UTC
    network_mode: "host"
    tmpfs: 
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true